use std::collections::VecDeque;

const WALL_STYLE: u8 = 11;
const DOOR_STYLE: u8 = 15;

#[derive(Clone, Copy, Debug)]
pub(super) struct WorkbookMapDesign {
    pub(super) name: &'static str,
    pub(super) width: usize,
    pub(super) height: usize,
    pub(super) spawn: [i32; 2],
    encoded_styles: &'static str,
}

#[derive(Clone, Debug)]
pub(super) struct DecodedWorkbookMap {
    pub(super) styles: Vec<u8>,
    pub(super) enclosed: Vec<bool>,
    pub(super) exterior: Vec<bool>,
}

impl WorkbookMapDesign {
    pub(super) fn decode(self) -> DecodedWorkbookMap {
        let bytes = decode_base64(self.encoded_styles);
        let mut styles = vec![0; self.width * self.height];
        let mut cursor = 0;
        let mut position = 0;
        while cursor < bytes.len() {
            position += read_varint(&bytes, &mut cursor);
            let length = read_varint(&bytes, &mut cursor);
            let style = bytes[cursor];
            cursor += 1;
            let end = position + length;
            assert!(
                end <= styles.len(),
                "{} workbook map data exceeds its declared bounds",
                self.name
            );
            styles[position..end].fill(style);
            position = end;
        }

        let mut exterior = vec![false; styles.len()];
        let mut queue = VecDeque::new();
        for x in 0..self.width {
            enqueue_exterior(x, &styles, &mut exterior, &mut queue);
            enqueue_exterior(
                (self.height - 1) * self.width + x,
                &styles,
                &mut exterior,
                &mut queue,
            );
        }
        for z in 0..self.height {
            enqueue_exterior(
                z * self.width,
                &styles,
                &mut exterior,
                &mut queue,
            );
            enqueue_exterior(
                z * self.width + self.width - 1,
                &styles,
                &mut exterior,
                &mut queue,
            );
        }
        while let Some(index) = queue.pop_front() {
            let x = index % self.width;
            let z = index / self.width;
            if x > 0 {
                enqueue_exterior(
                    index - 1,
                    &styles,
                    &mut exterior,
                    &mut queue,
                );
            }
            if x + 1 < self.width {
                enqueue_exterior(
                    index + 1,
                    &styles,
                    &mut exterior,
                    &mut queue,
                );
            }
            if z > 0 {
                enqueue_exterior(
                    index - self.width,
                    &styles,
                    &mut exterior,
                    &mut queue,
                );
            }
            if z + 1 < self.height {
                enqueue_exterior(
                    index + self.width,
                    &styles,
                    &mut exterior,
                    &mut queue,
                );
            }
        }
        let enclosed = styles
            .iter()
            .zip(&exterior)
            .map(|(style, exterior)| !*exterior && !blocks_exterior_flood(*style))
            .collect();
        DecodedWorkbookMap {
            styles,
            enclosed,
            exterior,
        }
    }

    pub(super) fn centered_offset(self, index: usize) -> [i32; 2] {
        let x = index % self.width;
        let z = index / self.width;
        [
            x as i32 - (self.width as i32 - 1) / 2,
            z as i32 - (self.height as i32 - 1) / 2,
        ]
    }
}

fn blocks_exterior_flood(style: u8) -> bool { matches!(style, WALL_STYLE | DOOR_STYLE) }

fn enqueue_exterior(
    index: usize,
    styles: &[u8],
    exterior: &mut [bool],
    queue: &mut VecDeque<usize>,
) {
    if !exterior[index] && !blocks_exterior_flood(styles[index]) {
        exterior[index] = true;
        queue.push_back(index);
    }
}

fn decode_base64(encoded: &str) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(encoded.len() * 3 / 4);
    let mut accumulator = 0_u32;
    let mut bit_count = 0_u32;
    for byte in encoded.bytes() {
        let value = match byte {
            b'A'..=b'Z' => byte - b'A',
            b'a'..=b'z' => byte - b'a' + 26,
            b'0'..=b'9' => byte - b'0' + 52,
            b'+' => 62,
            b'/' => 63,
            b'=' => break,
            _ => continue,
        };
        accumulator = (accumulator << 6) | u32::from(value);
        bit_count += 6;
        if bit_count >= 8 {
            bit_count -= 8;
            bytes.push((accumulator >> bit_count) as u8);
            accumulator &= (1_u32 << bit_count).wrapping_sub(1);
        }
    }
    bytes
}

fn read_varint(bytes: &[u8], cursor: &mut usize) -> usize {
    let mut value = 0_usize;
    let mut shift = 0;
    loop {
        let byte = bytes[*cursor];
        *cursor += 1;
        value |= usize::from(byte & 0x7f) << shift;
        if byte & 0x80 == 0 {
            return value;
        }
        shift += 7;
        assert!(
            shift < usize::BITS,
            "invalid workbook map varint"
        );
    }
}

// Generated from D:\qq_download\地图.xlsm. Only geometry-bearing cell styles
// are retained; descriptions, macros, player tables, and workbook formulas are
// deliberately excluded.
pub(super) const ARROGANCE: WorkbookMapDesign = WorkbookMapDesign {
    name: "U.S.I 狂妄号",
    width: 216,
    height: 84,
    spawn: [0, -6],
    encoded_styles: "qgcWC0cGC3QBCwIDEAEDEAEDEAEDEAEDEAEBC0YBCwAEDQABC3MBCwMDEAEDEAEDEAEDEAEDEAIBC0UBCwAEDQABC3MBCwMDEAEDEAEDEAEDEAEDEAMBC0QBCwAEDQABC3MBCwAZDAABC0QBCwAEDQABC3MBCwAZDAABC0MBCwYBC3IBCwIVDAIBC0IBCwgBC3EBCwMCGwICGwIDDAIGEAMBCwABDEABCwADEAcpC0gBCwMCGwICGwIDDAIGEAQtCxMBCwEDECsEDQABCyENCxoBCwMCGwICGwIDDAIGEDEECw8BCwEDECsEDQABCyEBCwALDAABCwABIRkBCwMCGwICGwIDDAIGEDIDEAACCw0BCy8EDQABCyEBCwABDAMDEAADGQABDAABCwABIQABIxgBCwMCGwICGwIDDAIGEAADGQEqCwQDEAEBCw0BCy8EDQABCyEBCwABDAMDEAADGQABDAABCwABIQADIwABJBUBCwsDDAIGEAADGQABCwABDAAoGgABCwQDEAEBCw0BCy8EDQABCyEBCwABDAMDEAADGQABDAABCwABIQADIwABJAABJQABJhMBCwsDDAIGEAADGQABCwApGgABCwgBCw0BCy8EDQABCyEBCwABDAkBDAABCwABIQADIwABJAABJQACJgEBJhABCwMCGwICGwIDDAIGEAMBCwApGgABCwgBCw0BCy8EDQABCyEBCwABDAYDEAABDAABCwABIQADIwABJAABJQACJhIBCwMCGwICGwIDDAIGEAMBCwApGgABCwICGwQBCw0BCy8EDQABCyEBCwABDAYCDAABEAABDAABCwABIQADIwABJAABJQABJgMBJg8BCwMCGwICGwIDDAIGEAMBCwApGgABCwICGwQBCw0BCwspCyEBCwABDAYDEAABDAABCwABIQADIwABJBUBCwMCGwICGwIDDAIGEAMBCwApGgABCwICGwQBCw0BCwoBCwABIUkBCwABDAkBDAABCwABIQABIxgBCwMCGwICGwIDDAIGEAMBCwApGgABCwgBCw0BCwoBCwABIQABI0gBCwABDAkBDAABCwABIRkBCwsDDAsBCwApGgABCwgBCw0BCwoBCwABIQADIwABJCQTIQABCw0BCwABDAkBDAABCxoBCwsDDAsBCwApGgABCwgBCw0BCwoBCwABIQADIwABJAABJQABJiIBIQABDAAQIgABDAAPCwABDAocCwsDDAsBCwApGgABCwgPCwABDAkBCwABIQADIwABJAABJQACJiEBIQABDAADGQ0BDAACCwABGgABCwABGgABCwACGgABCwABGgABCwABGgABCwABGgABCwABDAoCCwABGgABCwABGgABCwABGgABCwACGgABCwABGgABCwABGgAFCwABGgABCwABGgACCwABGgABCwABGgABCwABDAoDDAsBCwABDAAoGgABCwcBDAACCwABGgABCwABGgABCwACGgABCwABGgABCwABGgABCwABGgABCwABDAkBCwABIQAEJAABJQACJiEBIQABDAADGQwBDAABCw8BCwABDBgBCwABDAsBCwABDAkDDAwBCwAoGgABCwYBDAABCw8BCwABDAgBCwABIQAEJAABJQACJiEBIQABDAADGQwBCxEBCxkBCwwBCwkDDA0pCwYBCxEBCwgBCwABIQAEJAABJQACJiEBIQABDAICGwsBDxEBDxkBDwwBDwkDDDwBDxEBDwgBCwABIQADJAACJQAHJhwBIQABDAICGwsBDxEBDxkBDwwBDwkDDDwBDxEBDwgBCwABIQADJAACJQAPJhQBIQABDAICGwADEAgBDxEBDxkBDwwBDwkDDBADCwMDCwMDCwMDCwMDCwMDCwsBDxEBDwgBCwABIQADJAACJQAVJgQBJgkBIQABDAICGwADEAgBDxEBDxkBDwwBDwkDDBADCwMDCwMDCwMDCwMDCwMDCwsBDxEBDwgBCwABIQADJAACJQAXJgMBJggBIQABDAICGwADEAgBDxEBDxkBDwwBDwkDDBADCwMDCwMDCwMDCwMDCwMDCwsBDxEBDwgBCwABIQADJAACJQAVJgMBJgQBJgUBIQABDAICGwsBDxEBDxkBDwwBDwkDDDwBDxEBDwgBCwABIQADJAACJQAPJhQBIQABDAICGwsBDxEBDxkBDwwBDwkDDDwBDxEBDwgBCwABIQADJAACJQAHJhwBIQABDAADGQwBCxEBCxkBCwwBCwkDDA0pCwYBCxEBCwgBCwABIQAEJAABJQACJiEBIQABDAADGQwBDAABCw8BCwABDBgBCwABDAsBCwABDAkDDAwBCwAoGgABCwYBDAABCw8BCwABDAgBCwABIQADIwABJAABJQACJiEBIQABDAADGQ0BDAACCwABGgABCwABGgABCwACGgABCwABGgABCwABGgABCwABGgABCwABDAoCCwABGgABCwABGgABCwABGgABCwACGgABCwABGgABCwABGgAFCwABGgABCwABGgACCwABGgABCwABGgABCwABDAoDDAsBCwABDAAoGgABCwcBDAACCwABGgABCwABGgABCwACGgABCwABGgABCwABGgABCwABGgABCwABDAkBCwABIQADIwABJAABJQACJiEBIQASDAAPCwABDAocCwsDDAsBCwApGgABCwgPCwABDAkBCwABIQADIwABJAABJQACJiETIQABCw0BCwABDAkBDAABCxoBCwsDDAsBCwApGgABCwgBCw0BCwoBCwABIQADIwABJAABJQABJkMBCwABDAkBDAABCwABIRkBCwsDDAsBCwApGgABCwgBCw0BCwoBCwABIQADIwABJEUBCwABDAkBDAABCwABIQABIxgBCwMCGwICGwIDDAIGEAMBCwApGgABCwgBCw0BCwoBCwABIQABI0gBCwABDAkBDAABCwABIQADIwABJBUBCwMCGwICGwIDDAIGEAMBCwApGgABCwICGwQBCw0BCwoBCwABIUkBCwABDAkBDAABCwABIQADIwABJAABJQABJgQBJg4BCwMCGwICGwIDDAIGEAMBCwApGgABCwICGwQBCw0BCwspCyEBCwABDAkBDAABCwABIQADIwABJAABJQACJhIBCwMCGwICGwIDDAIGEAMBCwApGgABCwICGwQBCw0BCy8EDQABCyEBCwABDAkBDAABCwABIQADIwABJAABJQACJgEBJhABCwMCGwICGwIDDAIGEAMBCwApGgABCwgBCw0BCy8EDQABCyEBCwABDAMDEAADGQABDAABCwABIQADIwABJAABJQABJhMBCwsDDAIGEAADGQABCwApGgABCwgBCw0BCy8EDQABCyEBCwABDAMDEAADGQABDAABCwABIQADIwABJBUBCwsDDAIGEAADGQABCwABDAAoGgABCwQDEAEBCw0BCy8EDQABCyEBCwABDAMDEAADGQABDAABCwABIQABIxgBCwMCGwICGwIDDAIGEAADGQEqCwQDEAEBCw0BCy8EDQABCyEBCwALDAABCwABIRkBCwMCGwICGwIDDAIGEDIDEAACCw0BCy8EDQABCyENCxoBCwMCGwICGwIDDAIGEDEECw8BCy8EDQABC0gBCwMCGwICGwIDDAIGEAQtCxMBCwIDECoEDQABC0gBCwMCGwICGwIDDAIGEAMBCwABDEABCwEDEAYpC0gBCwIVDAIBC0IBCwADEAUBC3EBCwAZDAABC0MBCwYBC3IBCwAZDAABC0QBCwAEDQABC3MBCwMDEAEDEAEDEAEDEAEDEAMBC0QBCwAEDQABC3MBCwMDEAEDEAEDEAEDEAEDEAIBC0UBCwAEDQABC3QBCwIDEAEDEAEDEAEDEAEDEAEBC0YBCwAEDQABC3UWC0cGCw==",
};

pub(super) const NIFFY: WorkbookMapDesign = WorkbookMapDesign {
    name: "U.S.I Niffy女皇号空间站",
    width: 163,
    height: 76,
    spawn: [0, 0],
    encoded_styles: "6QMNC5YBAQsACwwAAQuWAQELAAEMAAMZAAMQAwEMAAELlgEBCwABDAADGQADEAMBDAABC5YBAQsAAQwAAxkAAxADAQwAAQuWAQELAAEMCQEMAAELlgEBCwABDAkBDAABC5YBAQsAAQwBAhsDAhsBAQwAAQuWAQELAAEMAQIbAwIbAQEMAAELlgEBCwABDAECGwMCGwEBDAABC5YBAQsAAQwJAQwAAQs8FQtFBAsABQ8ABAs8AQsAAxkCAxkDAxkCAxkAAQtIAQsFAQs/AQsAAxkCAxkDAxkCAxkAAQtIAQsAARoDARoAAQs/AQsAAxkCAxkDAxkCAxkAGAsxAQsFAQs/AQsTAQ8FBA0EBA0FAQsxAQsAARoDARoAAQs/AQsTAQ8FBA0EBA0FAQsxAQsFAQs/AQsTAQ8FBA0EBA0FAQsxAQsAARoDARoAAQs/AQsECxkEAQsABA0BBA0EBA0BBA0AAQsxAQsFAQs/AQsECxkEAQsABA0OBA0AAQsxAQsAARoDARoAAQs/AQsECxkEAQsABA0OBA0AAQsxAQsFEAswAQsECxkEAQsABA0OBA0AAQsxAQsHAxAEAxADMgsECxkEAQsWAQsxAQsAAhISAQ8wAQ8ECxkEAQsABA0BAhIBAhIBAhIBAhICBA0AAQsxAQsAAhESAQ8wAQ8ECxkEAQsABA0BAhEBAhEBAhEBAhECBA0AAQsxAQsAAhISAQ8wAQ8ECxkEAQsABA0BAhIBAhIBAhIBAhICBA0AAQsxAQsAAxABAxABAxABAxABAxABDAsAAw8ADwsAAw8AEQsECxkEAQsABA0OBA0AAQsxAQsAAxABAxABAxABAxABAxABAQsKAQsDAQsNAQsDAQsPAQsECxkEAQsFAhIBAhIBAhIBAhIGAQsxAQsAAxABAxABAxABAxABAxABAQsKAQsDAQsNAQsAAhEBAQsPAQsECxkEAQsABA0BAhEBAhEBAhEBAhECBA0AAQsxFgsKAQsDAQsNBQsPAQsECxkEAQsABA0BAhIBAhIBAhIBAhICBA0AAQtRAQsDAQshAQsECxkEAQsABA0BAxABAxABAxACBA0AAQtRAQsDAQshAQsTAQsABA0BAxABAxABAxACBA0AAQtRAQsDAQshAQsTAQsFAxABAxABAxAGAQtRAQsDAQshAQsTGAtRAQsDAQsbBQsBAQsTAQtoAQsDAQsbAQsAAxkAAQsBAQsTAQtoAQsDAQsbAQsAAxkAAQsBAQsTAQtoAQsDAQsbAQsAAxkAAQsBAQsTAQtoAQsDAQsbAQsDAwsTAQtoAQsDAQsbAQsFAQ8TAQtoAQsDAQsbAQsFAQ8TAQtoAQsDAQsbAQsFAQ8TAQtoAQsDAQsbAQsDFwtoAQsDAQsMCwsEAQsDAQteFQsLAQsDAQsMAQsACRkAAQsEAQsDAQteAQsAAxkDAxABAxADAxkAAQsLAQsDAQsMAQsACRkAAQsEAQsDAQteAQsAAxkDAxABAxADAxkAAQsLAQsDAQsMAQsACRkAAQsEAQsDAQteAQsAAxkDAxABAxADAxkAAQsLAQsDAQsMAQsJAQsEAQsDAQteAQsTAQsLAQsDAQsMAQsJAQsEAQsDAQteAQsABA0PDQsDEAsFCAsDAQteAQsABA0PAQ8PAQ8VBhAEAQteAQsABA0PAQ8PAQ8VBhAEAQteAQsABA0PAQ8PAQ8BAhsCAhsOBhAEAQsGBwtRAQsTEQsBAhsCAhsYAQsCBAsAAxkBAxkABAtNAQsABA0MAxAAAQsPAQsBAhsCAhsYAwsAAxkBAxkBAxkBAxkAAgtLAQsABA0MAxAAAQsPAQsfAQ8CAxkBAxkBAxkBAxkBAQtLAQsABA0MAxAAAQsPAQsBAhsCAhsCAyACAyACAyACAyAEAQ8CAxkJAxkBAQtLAQsABA0PAQsPAQsBAhsCAhsCAyACAyACAyACAyAEAQ8SAQtLAQsTAQsPAQsBAhsCAhsCAyACAyACAyACAyAEAQsSAQtLAQsABA0PAQsPIQsBAhsCAhsEAhsCAhsBAQtLAQsABA0PAQsvAQsBAhsCAhsEAhsCAhsBAQtLAQsABA0PAQsvAQsBAhsCAhsEAhsCAhsBAQtLAQsABA0PAQsvAQsSAQtLAQsTAQsvAQsBAhsCAhsEAhsCAhsBAQtLAQsABA0JBhAAAQsvAQsBAhsCAhsEAhsCAhsBAQtLAQsABA0JBhAAAQsvAQsBAhsCAhsEAhsCAhsBAQtLAQsABA0JBhAAAQsvAQsSAQtLAQsABA0JBhAAAQsvAQsBAxABAxACAxABAxABAQtLAQsNBhAAAQsvAQsBAxABAxACAxABAxABAQtLAQsNBhAAAQsvAQsBAxABAxACAxABAxABAQtLAQsAAxkBAxABAxAFAxkAAQsvFAtLAQsAAxkBAxABAxAFAxkAAQuOAQELAAMZAQMQAQMQBQMZAAELjgEVCw==",
};

pub(super) const KYO: WorkbookMapDesign = WorkbookMapDesign {
    name: "U.S.I Kyo空间站",
    width: 161,
    height: 75,
    spawn: [-33, 0],
    encoded_styles: "wgIVCwcVC3ABCwATDAABCwcBCwATDAABC3ABCwABDAAGGQEDEAEGGQABDAABCwcBCwABDAAEDQMCEQECEQECEQIBDAABC3ABCwABDAAGGQEDEAEGGQABDAABCwcBCwABDAAEDQMCEgECEgECEgIBDAABC3ABCwABDAAGGQEDEAEGGQABDAABCwcBCwABDAAEDQ0BDAABC3ABCwABDBEBDAABCwcBCwABDAAEDQMCEQECEQECEQIBDAABC3ABCwABDBEBDAABCwcBCwABDAcCEgECEgECEgIBDAABC3ABCwABDBEBDAABCwcBCwABDAAEDQ0BDAABC3ABCwABDBEBDAABCwcBCwABDAAEDQMEEAEEEAEBDAABC3ABCwABDBEBDAABCwcBCwABDAAEDQMEEAEEEAEBDAABC3ABCwABDBEBDAABCwcBCwABDAAEDQMEEAEEEAEBDAABC3ABCwABDBEBDAABCwcBCwABDAcEEAEEEAEBDAABC3ABCwABDBEBDAABCwcBCwABDAAEDQMEEAEEEAEBDAABC3ABCwABDBEBDAABCwcBCwABDAAEDQMEEAEEEAEBDAABC3ABCwABDAADGQsDGQABDAABCwcBCwABDAAEDQMEEAEEEAEBDAABC3ABCwABDAADGQsDGQABDAABCwcBCwABDAAEDQ0BDAABC3ABCwABDAADGQsDGQABDAABCwcBCwABDBEBDAABC3ABCwAIDAMIDAABCwcBCwAIDAMIDAABC3AJCwADDwAJCwcJCwADDwAJC3cBCwABGgMBGgABCxUBCwABGgMBGgABC34BCwUBCxUBCwUBC34BCwABGgMBGgABCxUBCwABGgMBGgABC34BCwUBCxUBCwUBC34BCwABGgMBGgABCxUBCwABGgMBGgABC34BCwUBCxUBCwUBC34CCwMCCxUCCwADDwACC3cJCwMJCwcJCwMJC3ABCwAIDAMIDAABCwcBCwAIDAMIDAABC3ABCwABDAADGQEDGQMDGQEDGQABDAABCwcBCwABDBEBDAABC3ABCwABDAADGQEDGQMDGQEDGQABDAABCwcBCwABDBEBDAABC3ABCwABDAADGQEDGQMDGQEDGQABDAABCwcBCwABDBEBDAABC3ABCwABDBEBDAABCwcBCwABDBEBDAABC3ABCwABDAADGQ4BDAAJCwABDBEBDAABC3ABCwABDAADGQ4BDAACCwEBGgEBGgEBGgABCwABDBEBDAABC3ABCwABDAADGRABDwYBDw8DGQABDAABC3ABCwABDBMBDwYBDw8DGQABDAABC3ABCwABDAADGRABDwYBDw8DGQABDAABC3ABCwABDAADGQ4BDAACCwEBGgEBGgEBGgABCwABDBEBDAABC3ABCwABDAADGQ4BDAAJCwABDBEBDAABC3ABCwABDBEBDAABCwcBCwABDBEBDAABC3ABCwABDAADGQEDGQMDGQEDGQABDAABCwcBCwABDAADEAsDEAABDAABC3ABCwABDAADGQEDGQMDGQEDGQABDAABCwcBCwABDAADEAsDEAABDAABC3ABCwABDAADGQEDGQMDGQEDGQABDAABCwcBCwABDAADEAsDEAABDAABC3ABCwATDAABCwcBCwATDAABC3AVCwcVCw==",
};

pub(super) const ARBITRATOR: WorkbookMapDesign = WorkbookMapDesign {
    name: "U.S.I 女仲裁者号空间站",
    width: 161,
    height: 110,
    spawn: [0, 0],
    encoded_styles: concat!(
        "gQMVC4wBAQsAEwwAAQuMAQELAAEMBAMZAAMQAAMZBAEMAAELjAEBCwABDAQDGQADEAADGQQBDAABC4wBAQsAAQwEAxkAAxAAAxkE",
        "AQwAAQuMAQELAAEMEQEMAAELjAEBCwABDBEBDAABC4wBAQsAAQwRAQwAAQuMAQELAAEMEQEMAAELjAEBCwABDBEBDAABC4wBAQsA",
        "AQwRAQwAAQuMAQELAAEMEQEMAAELjAEBCwABDBEBDAABC4wBAQsAAQwRAQwAAQuMAQELAAEMEQEMAAELjAEBCwABDBEBDAABC4wB",
        "AQsAAQwRAQwAAQuMAQELAAgMAwgMAAELjAEJCwMJC5MBAgsAAw8AAguaAQELAAEaAwEaAAELmgEBCwUBC5oBAQsAARoDARoAAQua",
        "AQELBQELmgEBCwABGgMBGgABC5oBAQsFAQuaAQELAAEaAwEaAAELmgEBCwUBC5oBAQsAARoDARoAAQuaAQELBQELmgEBCwABGgMB",
        "GgABC5oBAQsFAQuaAQELAAEaAwEaAAELmgEBCwUBC5oBAQsAARoDARoAAQuaAQELBQELmgEBCwABGgMBGgABC5oBAQsFAQuaAQEL",
        "AAEaAwEaAAELmgEBCwUBC5oBAQsAARoDARoAAQuaAQELBQELmgEBCwABGgMBGgABC5oBAQsFAQuaAQILAAMPAAILZRULGQkLAwkL",
        "GRULMAELABMMAAELGQELAAgMAwgMAAELGQELABMMAAELMAELAAEMEQEMAAELGQELAAEMAAMQAAMZBQMZAAMQAAEMAAELGQELAAEM",
        "EQEMAAELMAELAAEMAAQNDQEMAAELGQELAAEMAAMQAAMZBQMZAAMQAAEMAAELGQELAAEMDQQNAAEMAAELMAELAAEMAAQNDQEMAAEL",
        "GQELAAEMAAMQAAMZBQMZAAMQAAEMAAELGQELAAEMDQQNAAEMAAELMAELAAEMAAQNDQEMAAELGQELAAEMEQEMAAELGQELAAEMDQQN",
        "AAEMAAELMAELAAEMAAQNDQEMABsLAAEMEQEMABsLAAEMDQQNAAEMAAELMAELAAEMEQEMAAILAQEaAQEaAQEaAQEaAQEaAQEaAQEa",
        "AQEaAQEaAQEaAQEaAQEaAAELAAEMEQEMAAILAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAAELAAEMEQEMAAEL",
        "MAELAAEMEwEPGAEPAAEMBwMQCQEPGAEPEgEMAAELMAELAAEMEwEPGAEPAAEMBwMQCQEPGAEPEgEMAAELMAELAAEMEwEPGAEPAAEM",
        "BwMQCQEPGAEPEgEMAAELMAELAAEMEQEMAAILAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAAELAAEMEQEMAAIL",
        "AQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAQEaAAELAAEMEQEMAAELMAELAAEMAAQNDQEMABsLAAEMEQEMABsLAAEM",
        "DQQNAAEMAAELMAELAAEMAAQNDQEMAAELGQELAAEMEQEMAAELGQELAAEMDQQNAAEMAAELMAELAAEMAAQNDQEMAAELGQELAAEMAAMQ",
        "CAMZAAMQAAEMAAELGQELAAEMDQQNAAEMAAELMAELAAEMAAQNDQEMAAELGQELAAEMAAMQCAMZAAMQAAEMAAELGQELAAEMDQQNAAEM",
        "AAELMAELAAEMEQEMAAELGQELAAEMAAMQCAMZAAMQAAEMAAELGQELAAEMEQEMAAELMAELABMMAAELGQELABMMAAELGQELABMMAAEL",
        "MBULGQkLAAMPAAkLGRULZQELAAEaAwEaAAELmgEBCwUBC5oBAQsAARoDARoAAQuaAQELBQELmgEBCwABGgMBGgABC5oBAQsFAQua",
        "AQELAAEaAwEaAAELmgEBCwUBC5oBAQsAARoDARoAAQuaAQELBQELmgEBCwABGgMBGgABC5oBAQsFAQuaAQELAAEaAwEaAAELmgEB",
        "CwUBC5oBAQsAARoDARoAAQuaAQELBQELmgEBCwABGgMBGgABC5oBAQsFAQuaAQELAAEaAwEaAAELmgEBCwUBC5oBAQsAARoDARoA",
        "AQuaAQELBQELmgEBCwABGgMBGgABC5oBAQsFAQuaAQILAAMPAAILkwEJCwMJC4wBAQsACAwDCAwAAQuMAQELAAEMEQEMAAELjAEB",
        "CwABDBEBDAABC4wBAQsAAQwRAQwAAQuMAQELAAEMEQEMAAELjAEBCwABDAECGwICGwoBDAABC4wBAQsAAQwBAhsCAhsKAQwAAQuM",
        "AQELAAEMAQIbAgIbCgEMAAELjAEBCwABDBEBDAABC4wBAQsAAQwBAhsCAhsKAQwAAQuMAQELAAEMAQIbAgIbCgEMAAELjAEBCwAB",
        "DAECGwICGwoBDAABC4wBAQsAAQwRAQwAAQuMAQELAAEMAAMQCwMQAAEMAAELjAEBCwABDAADEAsDEAABDAABC4wBAQsAAQwAAxAL",
        "AxAAAQwAAQuMAQELABMMAAELjAEVCw==",
    ),
};

pub(super) const ABANDONED: WorkbookMapDesign = WorkbookMapDesign {
    name: "废弃太空站",
    width: 161,
    height: 108,
    spawn: [0, 0],
    encoded_styles: "pTAVC4wBAQsFAgsFAgsFAQuMAQELBQILBQILBQELjAEBCwUCCwUCCwUBC4wBAQsFAgsFAgsFAQuMAQELBQILBQILBQELjAEBCwUCCwUCCwUBC4YBIQuAAQELBQELABMMAAELBQELgAEBCwUBCwABDAAEDQ0BDAABCwUBC4ABBwsAAQwABA0NAQwABwuAAQELBQELAAEMAAQNDQEMAAELBQELgAEBCwUBCwABDAAEDQ0BDAABCwUBC4ABBwsAAQwRAQwABwuAAQELBQELAAEMAAQNDQEMAAELBQELgAEBCwUBCwABDAAEDQMDEAADGQQBDAABCwUBC4ABBwsAAQwABA0DAxAAAxkEAQwABwuAAQELBQELAAEMAAQNAwMQAAMZBAEMAAELBQELgAEBCwUBCwABDBEBDAABCwUBC4ABBwsAAQwRAQwABwuAAQELBQELAAEMEQEMAAELBQELgAEBCwUBCwABDBEBDAABCwUBC4ABBwsAAQwRAQwABwuAAQELBQELAAEMEQEMAAELBQELgAEBCwUBCwATDAABCwUBC4ABDwsAAw8ADwuGAQELBQILBQILBQELjAEBCwUCCwUCCwUBC4wBAQsFAgsAAhEBAhEAAgsFAQuMAQELBQILAAISAQISAAILBQELjAEBCwUCCwACEQECEQACCwUBC4wBAQsFAgsAAhIBAhIAAgsFAQuMARUL",
};

pub(super) const XY_PLANET: WorkbookMapDesign = WorkbookMapDesign {
    name: "XY星",
    width: 115,
    height: 46,
    spawn: [-11, 0],
    encoded_styles: "cyIHAAELAAQNAAIHAAQNABUHAAQNAAIHAAQNAAELAAsTAD0HAAELAAQNAAIHAAQNABUHAAQNAAIHAAQNAAELAAsTACsHAAEIABEHAAELAAQNAAIHAAQNABUHAAQNAAIHAAQNAAELAAMTAAEUAAcTAD0HAAELAAQNAAIHAAQNABUHAAQNAAIHAAQNAAELAAsTAD0HAAELACkHAAELAAsTACIHAAEJABoHABQLAAMPABQLAAsTADcHAAYKAAcJAAEHAAIJAAEHAAQJAAEHAAEJAAEHAAEJABgHAAsTADcHAA0KAAEJAAIKAAEJAAQKAAEJAAEKAAIJABYKAA0TACkHAAEIAA0HAAMKAAEJAAMKAAEIAAEKAAEIAAQKAAEJAAUKAAEJAAEKAAEJABYKAAIHAA0TAAsHAAEJABwHAAEIAAEJAAEIAAoHAAoKAAEIACQKAAIHAA0TAAoHAAEIACgHAAsKAAEIACAKAAcHAAgTAAEUAAQTAAsHAAEIABcHAAEIAA4HAC0KAAQHABATAAYHAAEIAA8HAAEJAAwHAAEJAA4HACkKAAgHABATAAcHAAEJAA0HAAEIAAwHAAEIAAEHAAEIAA0HABoKAAEIAA4KAAgHAAkTAAEUAAYTADIHAAQKABUIAAEKAAEIAAIKABQHABATADMHAAEKAAIIAAkLAAMPAAkLAAEIAAEHAAEIABUHAAYTAAEUAAkTADMHAAEKAAIIAAELAAgMAwgMAAELAAEHAAEIABYHABATADMHAAEIAAEKAAEIAAELAAEMAAQNDQEMAAELAAEIABYHABETAA0HAAEJACUHAAIIAAEKAAELAAEMAAQNDQEMAAELABUHABMTAA0HAAEIACgHAAELAAEMAAQNCgMQAAEMAAELABUHABITACUHAAEIABEHAAELAAEMAAQNCgMQAAEMAAELABEHABYTACQHAAEIAAEJAAEIABAHAAELAAEMDgMQAAEMAAELABAHABcTACUHAAEIABEHAAELAAEMAAQNDQEMAAELAA4HABkTADcHAAELAAEMAAQNDQEMAAELAA4HABgTAAYHAAEJAA0HAAEJACMHAAELAAEMAAQNCgMQAAEMAAELAA4HABYTAAkHAAEIAAwHAAEIABUHAAEJAA0HAAELAAEMAAQNCgMQAAEMAAELAA4HABQTACoHAAEIAAQHAAEIAAwHAAELAAEMDgMQAAEMAAELAAwHAAsTAAEUAAkTACoHAAEJABIHAAELAAEMEQEMAAELAAkHABYTABIHAAEJABgHAAEIABMHAAELAAEMAAQNDQEMAAELAAcHAAgTAAMUAA0TABEHAAEIAC0HAAELAAEMAAQNBgMQAQMQAAEMAAELAAcHAAgTAAMUAAsTAEEHAAELAAEMAAQNBgMQAQMQAAEMAAELAAcHABMTAEQHAAELAAEMAAQNBgMQAQMQAAEMAAELAAcHABITADoHAAEJAAUHAAEIAAQHAAELABMMAAELAAUHABQTABwHAAEJAAkHAAEJAAYHAAEIAAsHAAEIAAQHAAEIAAEJAAUHAAkLAAMPAAkLAAUHABQTABQHAAEJAAgHAAEIAAgHAAEIAAUHAAEIAAEJAAEIABEHAAEIAAsHAAELBQELAAsHAAUTAAEUAAcTAAEUAAQTABgHAAEIABcHAAEIAAkHAAEJABQHAAELBQELAAsHABITADoHAAEIABQHAAELAAIRAQIRAAELAAoHABITAFAHAAELAAISAQISAAELAAoHABETAAwHAAEJAAEIAEMHAAELAAIRAQIRAAELAAoHABETAAwHAAEIAEQHAAELAAISAQISAAELAAoHABATADwHAAEIABUHAAcLAAUHAA0TAAEUAAUTAD0HAAEIAAEJAAEIAB4HABMTAGAHABITAF8HAA4TACwHAAEIACEHAAEIAAEJAAEIABQHAAUTAAEUAAITADAHAAEIAAEHAAEJAAEIAA0H",
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn workbook_maps_decode_to_their_exact_sheet_dimensions() {
        for design in [ARROGANCE, NIFFY, KYO, ARBITRATOR, ABANDONED, XY_PLANET] {
            assert_eq!(
                design.decode().styles.len(),
                design.width * design.height,
                "{}",
                design.name
            );
        }
    }

    #[test]
    fn workbook_maps_preserve_walls_doors_and_enclosed_floorplans() {
        for (design, expected_walls, expected_doors, expected_enclosed) in [
            (ARROGANCE, 1_033, 42, 5_275),
            (NIFFY, 716, 32, 3_288),
            (KYO, 334, 15, 1_394),
            (ARBITRATOR, 568, 24, 2_110),
            (ABANDONED, 295, 3, 623),
            (XY_PLANET, 139, 9, 353),
        ] {
            let decoded = design.decode();
            assert_eq!(
                decoded
                    .styles
                    .iter()
                    .filter(|style| **style == WALL_STYLE)
                    .count(),
                expected_walls,
                "{} walls",
                design.name
            );
            assert_eq!(
                decoded
                    .styles
                    .iter()
                    .filter(|style| **style == DOOR_STYLE)
                    .count(),
                expected_doors,
                "{} doors",
                design.name
            );
            assert_eq!(
                decoded
                    .enclosed
                    .iter()
                    .filter(|enclosed| **enclosed)
                    .count(),
                expected_enclosed,
                "{} enclosed cells",
                design.name
            );
        }
    }
}
